spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/finansys
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres


  jpa:
    hibernate:
#      ddl-auto: none
      ddl-auto: validate
      show-sql: true

logging:
  level:
    root: INFO
    com.finansys.backend: DEBUG

jwt:
  secret: xLGe6hb54PcRDv+DuJrdGDV2N0eCY4JEJYiMGVfeyVg=