spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5434/finansys
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}


  jpa:
    hibernate:
#      ddl-auto: none
      ddl-auto: validate
      show-sql: true

logging:
  level:
    root: INFO
    com.finansys.backend: DEBUG

jwt:
  secret: xLGe6hb54PcRDv+DuJrdGDV2N0eCY4JEJYiMGVfeyVg=

cors:
  allowed-origins:
    - "http://localhost:4200"
    - "http://localhost:3000"
    - "http://127.0.0.1:4200"
    - "http://127.0.0.1:3000"
    - "http://localhost:8081"
  allowed-methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "PATCH"
    - "OPTIONS"
  allowed-headers:
    - "*"
  allow-credentials: true

#  server:
#    port: 8080
#    servlet:
#      context-path: /api